config/routes.rb
Hackertracker::Application.routes.draw do
  resources :areas


  resources :unique_items do
    collection do
      post 'search'
    end
    resources :contacts
    resources :caveats
    resources :tutorials
    resources :tickets
    resources :logs
  end

  resources :settings

  resources :payments

  devise_for :users

  resources :users, :path => :members

  root to: 'pages#landing'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, 
            :birthday, :date_joined, :date_of_form, :ec_allergies, :ec_cell, 
            :ec_home, :ec_name, :ec_relation, :ec_second_cell, 
            :ec_second_home, :ec_second_name, :ec_second_relation, :handle, 
            :keycard_number, :level, :mailing_address, :name, :paypal_email, 
            :phone_number, :release_authorization, :sponsor_1_name, 
            :sponsor_2_name

  has_many :payments

  has_many :photos

  after_create :associate_payments

  def admin?
    role == "admin"
  end

  def set_admin(val)
    self.admin = val
  end

  def associate_payments
    Payment.unassociated.recurring.each do |p|
      if p.email.downcase == self.paypal_email.downcase
        p.user = self
        p.save
      end
    end
  end

  def latest_payment
    self.payments.order(:transaction_time).last
  end

  def generate_password
    self.password = Base64::encode64(rand.to_s[0..-4])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :admin_only

  # GET /users
  # GET /users.json
  def index
    @users = User.all.sort do |a,b| 
        a = a.latest_payment ? a.latest_payment.transaction_time : Time.now-365.days
        b = b.latest_payment ? b.latest_payment.transaction_time : Time.now-365.days
        a <=> b
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.generate_password

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="well">
    <h3>Member Info</h3>
    <%= f.text_field :name, placeholder: 'Member Name' %>
    <%= f.text_field :handle, placeholder: 'Handle / Nick' %>
    <%= f.text_field :email, placeholder: 'Contact Email' %>
    <%= f.text_field :paypal_email, placeholder: 'Paypal Email' %>
    <%= f.text_field :keycard_number, placeholder: 'Keycard Number' %>
    <%= f.label :birthday %>
    <%= datepicker :user, :birthday, @user.birthday %>
    <%= f.text_field :phone_number, placeholder: 'Phone Number' %>
    <%= f.text_field :mailing_address, placeholder: 'Mailing Address' %>
    <%= f.text_field :level, placeholder: 'Membership Level' %>
  </div>
  <div class="well">
    <h3>Sponsors</h3>
    <%= f.text_field :sponsor_1_name, placeholder: 'Sponsor 1' %>
    <%= f.text_field :sponsor_2_name, placeholder: 'Sponsor 2' %>
  </div>

  <div class="well">
    <h3>Dates</h3>
    <%= f.label :date_of_form %>
    <%= datepicker :user, :date_of_form, @user.date_of_form %>
    <%= f.label :date_joined %>
    <%= datepicker :user, :date_joined, @user.date_joined %>
  </div>

  <div class="well">
    <h3>Emergency Contact Info</h3>
    <%= f.text_field :ec_name, placeholder: 'Name'%>
    <%= f.text_field :ec_relation, placeholder: 'Relationship' %>
    <%= f.text_field :ec_home, placeholder: 'Home Phone' %>
    <%= f.text_field :ec_cell, placeholder: 'Cell Phone' %>
    <%= f.text_field :ec_second_name, placeholder: 'Name' %>
    <%= f.text_field :ec_second_relation, placeholder: 'Relationship' %>
    <%= f.text_field :ec_second_home, placeholder: 'Home Phone' %>
    <%= f.text_field :ec_second_cell, placeholder: 'Cell Phone' %>
    <%= f.text_field :ec_allergies, placeholder: 'Allergies' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<script type="text/javascript">
$(document).ready(function() {
  $('#page-users').each(function() {
    var $link = $(this);
    var $dialog = $('<div></div>')
      .load($link.attr('href') + ' #content')
      .dialog({
        autoOpen:  false,
        title:  $link.attr('title'),
        width:  500,
        height:  300,
        });

    $link.click(function() {
        $dialog.dialog('open');

        return false;

        });
    });
});
</script>


<h1>Listing users</h1>
<div class="well">
<table class="table table-striped table-bordered table-condensed">
  <tr>
    <th></th>
    <th>Name</th>
    <th>Handle</th>
    <th>Paypal email</th>
    <th>Phone number</th>
    <th>Level</th>
    <th>Date joined</th>
    <th>Last Payment</th>
  </tr>

<% @users.each_with_index do |user, i| %>
  <% late = user.latest_payment ? ( user.latest_payment.transaction_time < (Time.now - 33.days) ) : false %>
  <tr class="<%= 'late' if late %>">
    <td><%= i+1 %></td>
    <td><%= link_to user.name, user_path(user) %></td>
    <td><%= user.handle %></td>
    <td><%= user.paypal_email %></td>
    <td><%= user.phone_number %></td>
    <td><%= user.level %></td>
    <td><%= user.date_joined %></td>
    <td><%= user.latest_payment ? "#{user.latest_payment.amount} @ #{user.latest_payment.transaction_time}" : "(n/a)"%></td>
  </tr>
<% end %>
</table>
</div>
<br />

<%= link_to 'Create New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<!--<div class="alert">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <%= notice %>
</div>
-->

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Create Payment', new_payment_path %> |
<%= link_to 'Back', users_path %>

<br /><br />
<div class="well">
<p>
  <b>Name:</b>
  <%= @user.name %>
</p>
<p>
  <b>Handle:</b>
  <%= @user.handle %>
</p>

<p>
  <b>Release authorization:</b>
  <%= @user.release_authorization %>
</p>

<p>
  <b>Paypal email:</b>
  <%= @user.paypal_email %>
</p>

<p>
  <b>Keycard number:</b>
  <%= @user.keycard_number %>
</p>

<p>
  <b>Birthday:</b>
  <%= @user.birthday %>
</p>

<p>
  <b>Phone number:</b>
  <%= @user.phone_number %>
</p>

<p>
  <b>Mailing address:</b>
  <%= @user.mailing_address %>
</p>
</div>
<div class="well">
<p>
  <b>Sponsor 1 name:</b>
  <%= @user.sponsor_1_name %>
</p>

<p>
  <b>Sponsor 2 name:</b>
  <%= @user.sponsor_2_name %>
</p>

<p>
  <b>Level:</b>
  <%= @user.level %>
</p>
</div>
<div class="well">
<p>
  <b>Date of form:</b>
  <%= @user.date_of_form %>
</p>
<p>
  <b>Date joined:</b>
  <%= @user.date_joined %>
</p>
</div>
<div class="well">
<p>
  <b>Ec name:</b>
  <%= @user.ec_name %>
</p>

<p>
  <b>Ec relation:</b>
  <%= @user.ec_relation %>
</p>

<p>
  <b>Ec home:</b>
  <%= @user.ec_home %>
</p>

<p>
  <b>Ec cell:</b>
  <%= @user.ec_cell %>
</p>

<p>
  <b>Ec second name:</b>
  <%= @user.ec_second_name %>
</p>

<p>
  <b>Ec second relation:</b>
  <%= @user.ec_second_relation %>
</p>

<p>
  <b>Ec second home:</b>
  <%= @user.ec_second_home %>
</p>

<p>
  <b>Ec second cell:</b>
  <%= @user.ec_second_cell %>
</p>

<p>
  <b>Ec allergies:</b>
  <%= @user.ec_allergies %>
</p>
</div>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Create Payment', new_payment_path %> |
<%= link_to 'Back', users_path %>