config/routes.rb
Hackertracker::Application.routes.draw do
  resources :areas


  resources :unique_items do
    collection do
      post 'search'
    end
    resources :contacts
    resources :caveats
    resources :tutorials
    resources :tickets
    resources :logs
  end

  resources :settings

  resources :payments

  devise_for :users

  resources :users, :path => :members

  root to: 'pages#landing'
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  attr_accessible :body, :fuid, :url, :user_id, :user
  belongs_to :unique_item, :foreign_key => :fuid
  belongs_to :user
  validates_presence_of :fuid

  #before_save :get_oembed_if_possible
  after_save :touch_unique_item


  def touch_unique_item
  	self.unique_item.touch
  end

  # TODO: figure out how to get this to work well. it pulls an embed for us, but its not very nice. 
  def get_oembed_if_possible
    return if url.blank? # drop out if we dont even have a url to test

    embedly_api = Embedly::API.new :user_agent => 'Mozilla/5.0 (compatible; mytestapp/1.0; my@email.com)'
    obj = embedly_api.oembed :url => url

    return if obj.length < 1
    obj=obj.first

    # TODO: use obj.title for the title once we have titles
    self.body = obj.html
  end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  layout 'famiapp'

  # GET /tutorials
  # GET /tutorials.json
  def index
    @tutorials = Tutorial.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tutorials }
    end
  end

  # GET /tutorials/1
  # GET /tutorials/1.json
  def show
    @tutorial = Tutorial.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tutorial }
    end
  end

  # GET /tutorials/new
  # GET /tutorials/new.json
  def new
    @tutorial = Tutorial.new fuid: params[:unique_item_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tutorial }
    end
  end

  # GET /tutorials/1/edit
  def edit
    @tutorial = Tutorial.find(params[:id])
  end

  # POST /tutorials
  # POST /tutorials.json
  def create
    @tutorial = Tutorial.new(params[:tutorial])
    @tutorial.fuid = params[:unique_item_id]

    respond_to do |format|
      if @tutorial.save
        format.html { redirect_to @tutorial.unique_item, notice: 'Tutorial was successfully created.' }
        format.json { render json: @tutorial, status: :created, location: @tutorial }
      else
        format.html { render action: "new" }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tutorials/1
  # PUT /tutorials/1.json
  def update
    @tutorial = Tutorial.find(params[:id])

    respond_to do |format|
      if @tutorial.update_attributes(params[:tutorial])
        format.html { redirect_to @tutorial.unique_item, notice: 'Tutorial was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutorials/1
  # DELETE /tutorials/1.json
  def destroy
    @tutorial = Tutorial.find(params[:id])
    @tutorial.destroy

    respond_to do |format|
      format.html { redirect_to @tutorial.unique_item }
      format.json { head :no_content }
    end
  end
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/tutorials/_form.haml
= form_for [@tutorial.unique_item, @tutorial] do |f|
  - if @tutorial.errors.any?
    #error_explanation
      %h2
        = pluralize(@tutorial.errors.count, "error")
        prohibited this tutorial from being saved:
      %ul
        - @tutorial.errors.full_messages.each do |msg|
          %li= msg
  .row-fluid
    = f.text_area :body, :placeholder => 'Full tutorial body text', :class => 'span12'
  .row-fluid
    = "- OR -"
  %br/
  .row-fluid
    = f.text_field :url, :placeholder => 'http://url/to/tutorial', :class => 'span12'
  .row-fluid
    = f.submit :class => 'btn btn-info span12'

app/views/tutorials/edit.haml
%h1 Editing Tutorial
= render 'form'
= link_to 'Show', unique_item_tutorial_path(@tutorial.unique_item, @tutorial)
|
= link_to 'Back', unique_item_path(@tutorial.unique_item)

app/views/tutorials/index.haml
%h1 Listing tutorials
%table
  %tr
    %th Fuid
    %th User
    %th Body
    %th Url
    %th
    %th
    %th
  - @tutorials.each do |tutorial|
    %tr
      %td= tutorial.fuid
      %td= tutorial.user_id
      %td= tutorial.body
      %td= tutorial.url
      %td= link_to 'Show', tutorial
      %td= link_to 'Edit', edit_tutorial_path(tutorial)
      %td= link_to 'Destroy', tutorial, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Tutorial', new_tutorial_path

app/views/tutorials/new.haml
%h1 Add A Tutorial
= render 'form'

app/views/tutorials/show.haml
%h1
  Object:
  = @tutorial.unique_item.name

%h5 Tutorial:

%p#notice= notice

- if @tutorial.user
  %p
    %b User:
    = @tutorial.user.name

%pre= @tutorial.body
%br/

.row-fluid
  = link_to 'Edit', edit_unique_item_tutorial_path(@tutorial.unique_item, @tutorial), :class => 'btn btn-info span12'