config/routes.rb
Hackertracker::Application.routes.draw do
  resources :areas


  resources :unique_items do
    collection do
      post 'search'
    end
    resources :contacts
    resources :caveats
    resources :tutorials
    resources :tickets
    resources :logs
  end

  resources :settings

  resources :payments

  devise_for :users

  resources :users, :path => :members

  root to: 'pages#landing'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :fuid, :handle, :name, :phone, :user, :fuid, :unique_item
  belongs_to :unique_item, :foreign_key => :fuid
  validates_presence_of :fuid, :name

  after_save :touch_unique_item
  def touch_unique_item
  	self.unique_item.touch
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  layout 'famiapp'

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new fuid: params[:unique_item_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])
    @contact.fuid = params[:unique_item_id]

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact.unique_item, notice: 'Contact was successfully created.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to @contact.unique_item, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to @contact.unique_item }
      format.json { head :no_content }
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.haml
= form_for [@contact.unique_item, @contact] do |f|
  - if @contact.errors.any?
    #error_explanation
      %h2
        = pluralize(@contact.errors.count, "error")
        prohibited this contact from being saved:
      %ul
        - @contact.errors.full_messages.each do |msg|
          %li= msg
  .row-fluid
    = f.text_field :phone, :placeholder => '(407) 123-4567', :class => 'span12'
  .row-fluid
    = f.text_field :email, :placeholder => 'derp@freemails.com (email)', :class => 'span12'
  .row-fluid
    = f.text_field :name, :placeholder => 'Derp Derpston (name)', :class => 'span12'
  .row-fluid
    = f.text_field :handle, :placeholder => 'derpsix123 (handle)'
  .row-fluid
    = f.submit :class => 'btn btn-info span12'

app/views/contacts/edit.haml
%h1 Editing contact
= render 'form'
= link_to 'Show', unique_item_contact_path(@contact.unique_item, @contact)
|
= link_to 'Back', contacts_path

app/views/contacts/index.haml
%h1 Listing contacts
%table
  %tr
    %th Fuid
    %th Phone
    %th Email
    %th Name
    %th Handle
    %th
    %th
    %th
  - @contacts.each do |contact|
    %tr
      %td= contact.fuid
      %td= contact.phone
      %td= contact.email
      %td= contact.name
      %td= contact.handle
      %td= link_to 'Show', contact
      %td= link_to 'Edit', edit_contact_path(contact)
      %td= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Contact', new_unique_item_contact_path(@contact.unique_item)

app/views/contacts/new.haml
%h1 New contact
= render 'form'
= link_to 'Back', unique_item_path(@contact.unique_item)

app/views/contacts/show.haml
%p#notice= notice
%p
  %b Fuid:
  = @contact.fuid
%p
  %b Phone:
  = @contact.phone
%p
  %b Email:
  = @contact.email
%p
  %b Name:
  = @contact.name
%p
  %b Handle:
  = @contact.handle
= link_to 'Edit', edit_unique_item_contact_path(@contact.unique_item, @contact)
|
= link_to 'Back', unique_item_path(@contact.unique_item)