config/routes.rb
Hackertracker::Application.routes.draw do
  resources :areas


  resources :unique_items do
    collection do
      post 'search'
    end
    resources :contacts
    resources :caveats
    resources :tutorials
    resources :tickets
    resources :logs
  end

  resources :settings

  resources :payments

  devise_for :users

  resources :users, :path => :members

  root to: 'pages#landing'
end

app/models/log.rb
class Log < ActiveRecord::Base
  attr_accessible :body, :fuid, :user_id, :user, :fuid, :unique_item
  belongs_to :unique_item, :foreign_key => :fuid
  belongs_to :user
  validates_presence_of :fuid, :body

  after_save :touch_unique_item
  def touch_unique_item
  	self.unique_item.touch
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  layout 'famiapp'

  # GET /logs
  # GET /logs.json
  def index
    @logs = Log.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @logs }
    end
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
    @log = Log.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @log }
    end
  end

  # GET /logs/new
  # GET /logs/new.json
  def new
    @log = Log.new fuid: params[:unique_item_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @log }
    end
  end

  # GET /logs/1/edit
  def edit
    @log = Log.find(params[:id])
  end

  # POST /logs
  # POST /logs.json
  def create
    @log = Log.new(params[:log])
    @log.fuid = params[:unique_item_id]

    respond_to do |format|
      if @log.save
        format.html { redirect_to @log.unique_item, notice: 'Log was successfully created.' }
        format.json { render json: @log, status: :created, location: @log }
      else
        format.html { render action: "new" }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /logs/1
  # PUT /logs/1.json
  def update
    @log = Log.find(params[:id])

    respond_to do |format|
      if @log.update_attributes(params[:log])
        format.html { redirect_to @log.unique_item, notice: 'Log was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log = Log.find(params[:id])
    @log.destroy

    respond_to do |format|
      format.html { redirect_to @log.unique_item }
      format.json { head :no_content }
    end
  end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.haml
= form_for [@log.unique_item, @log] do |f|
  - if @log.errors.any?
    #error_explanation
      %h2
        = pluralize(@log.errors.count, "error")
        prohibited this log from being saved:
      %ul
        - @log.errors.full_messages.each do |msg|
          %li= msg
  .row-fluid
    = f.text_area :body, :class => 'span12'
  .row-fluid
    = f.submit :class => 'btn btn-info span12'

app/views/logs/edit.haml
%h1 Editing log
= render 'form'
= link_to 'Show', unique_item_log_path(@log.unique_item, @log)
|
= link_to 'Back', unique_item_path(@log.unique_item)

app/views/logs/index.haml
%h1 Listing logs
%table
  %tr
    %th Fuid
    %th User
    %th Body
    %th
    %th
    %th
  - @logs.each do |log|
    %tr
      %td= log.fuid
      %td= log.user_id
      %td= log.body
      %td= link_to 'Show', log
      %td= link_to 'Edit', edit_log_path(log)
      %td= link_to 'Destroy', log, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Log', new_log_path

app/views/logs/new.haml
%h1 New log
= render 'form'
= link_to 'Back', unique_item_path(@log.unique_item)

app/views/logs/show.haml
%p#notice= notice
%p
  %b Fuid:
  = @log.fuid
%p
  %b User:
  = @log.user_id
%p
  %b Body:
  = @log.body
= link_to 'Edit', edit_unique_item_log_path(@log.unique_item, @log)
|
= link_to 'Back', unique_item_path(@log.unique_item)